[package]
name = "raflash"
version = "1.0.0"
authors = []

[addresses]
module_addr = "_"

[dependencies]
AptosFramework = { local = "/Users/nadhir/Documents/Procyon/Aptos/aptos-core-main/aptos-move/framework/aptos-framework" , rev="testnet" }
AptosTokenObjects = { local = "/Users/nadhir/Documents/Procyon/Aptos/aptos-core-main/aptos-move/framework/aptos-token-objects", rev = "testnet" }

[dev-dependencies]
